### ISSUE TITLE
New config file should be like this

### ISSUE THREAD

**Issue by kieras** [kieras/sntzr#1]
```yaml
---
global_regex:
  'gr://machine_name': '[A-Z0-9-]+'

patterns:
  - 'pattern': '<MachineName>[A-Z0-9-]+</MachineName>'
    'replace': 'machine_name'

  - 'pattern': '<EMailAddress>.*?</EMailAddress>'
    'replace': '<EMailAddress>john@acme.com</EMailAddress>'
  
  - 'pattern': 'gr://machine_name'
    'replace': 'machine_name'
    'activated': false
```
